### ISSUE TITLE
docker - create docker build

### ISSUE THREAD

**Issue by beckscode** [Sky360-Repository/gui-openmct#1]
I am not a docker expert, but I believe we need two docker builds that will be initiated using docker-compose. 

A.
The first build will be a mock representation of the sky360 station. It should contain ROS2, Python, Rosbridge 'loaded' on an x86 linux ubuntu environment.
B.
The second build should have ROS2, python, node.js, all of the code within the openmct-gui repo and 'loaded' on an x86 linux ubuntu environment.  Both docker builds should communicate via ROS2 and a network connection.  
C.
The first and second builds should be able to be spun up using docker-compose, hopefully, by using one command from the docker-compose cli.

**Comment by gerlynm** [comment]
@beckscode is this issue still on?

**Comment by beckscode** [comment]
Hello @imjerri 

Yes, would you like to help us out on that?  I can fill you in on the details in our discord gui chat. It will be one docker build that will work with others that have already been built.  Thank you

**Comment by gerlynm** [comment]
@beckscode can you please share the further details ?

**Comment by beckscode** [comment]
> @beckscode can you please share the further details ?

Hi Imjerri, I updated the ticket page with further details. I hope it explains better what we're interested in.  Thank you
